#!/usr/bin/env python3
# ChArUco 5x7 board generator — Phase 5 hand-eye calibration.
# Prints at A4, 100% scale. Square size MUST be verified with a ruler after printing.

import sys
from pathlib import Path

import cv2
import cv2.aruco as aruco
import numpy as np
from PIL import Image, ImageDraw, ImageFont

# --- Board-Parameter (nach dem ersten Druck NIEMALS ändern) ---
SQUARES_X = 5              # Anzahl Spalten
SQUARES_Y = 7              # Anzahl Zeilen
SQUARE_LENGTH_MM = 30.0    # Kantenlänge eines Quadrats
MARKER_LENGTH_MM = 22.0    # ArUco Marker-Kante (im Quadrat, ~0.73x square)
DICT_ID = aruco.DICT_5X5_100
DICT_NAME = "DICT_5X5_100"

# --- A4 Druck ---
DPI = 300
A4_W_MM = 210.0
A4_H_MM = 297.0


def mm2px(mm: float) -> int:
    return int(round(mm * DPI / 25.4))


def main() -> int:
    # Script lives in <pkg>/scripts/ — write outputs to <pkg>/boards and <pkg>/config.
    pkg_root = Path(__file__).resolve().parent.parent
    boards_dir = pkg_root / "boards"
    cfg_dir = pkg_root / "config"
    boards_dir.mkdir(parents=True, exist_ok=True)
    cfg_dir.mkdir(parents=True, exist_ok=True)

    dictionary = aruco.getPredefinedDictionary(DICT_ID)
    board = aruco.CharucoBoard(
        (SQUARES_X, SQUARES_Y),
        SQUARE_LENGTH_MM / 1000.0,
        MARKER_LENGTH_MM / 1000.0,
        dictionary,
    )

    board_w_px = mm2px(SQUARES_X * SQUARE_LENGTH_MM)
    board_h_px = mm2px(SQUARES_Y * SQUARE_LENGTH_MM)
    board_img = board.generateImage((board_w_px, board_h_px), marginSize=0, borderBits=1)

    a4_w_px = mm2px(A4_W_MM)
    a4_h_px = mm2px(A4_H_MM)
    canvas = Image.new("RGB", (a4_w_px, a4_h_px), "white")

    # Board auf der Seite horizontal zentrieren, oben 20 mm Abstand lassen
    off_x = (a4_w_px - board_w_px) // 2
    off_y = mm2px(20)
    canvas.paste(Image.fromarray(board_img).convert("RGB"), (off_x, off_y))

    draw = ImageDraw.Draw(canvas)
    try:
        font_md = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 32
        )
        font_sm = ImageFont.truetype(
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 24
        )
    except OSError:
        font_md = ImageFont.load_default()
        font_sm = font_md

    text_y = off_y + board_h_px + mm2px(12)
    lines = [
        f"ChArUco {SQUARES_X}x{SQUARES_Y}",
        f"square = {SQUARE_LENGTH_MM:.1f} mm   marker = {MARKER_LENGTH_MM:.1f} mm",
        f"dict   = {DICT_NAME}",
        "Print at 100 % scale (NO fit-to-page).",
    ]
    for ln in lines:
        draw.text((mm2px(15), text_y), ln, fill="black", font=font_sm)
        text_y += mm2px(7)

    # 50 mm Referenzlineal — nach dem Druck mit einem Lineal prüfen
    ruler_y = text_y + mm2px(6)
    ruler_x0 = mm2px(15)
    ruler_x1 = ruler_x0 + mm2px(50)
    draw.line([(ruler_x0, ruler_y), (ruler_x1, ruler_y)], fill="black", width=4)
    for i in range(6):
        x = ruler_x0 + mm2px(10 * i)
        h = mm2px(5) if i % 5 == 0 else mm2px(3)
        draw.line([(x, ruler_y), (x, ruler_y + h)], fill="black", width=3)
    draw.text(
        (ruler_x0, ruler_y + mm2px(7)),
        "Reference 0-50 mm (verify after print)",
        fill="black",
        font=font_sm,
    )

    png_path = boards_dir / f"charuco_{SQUARES_X}x{SQUARES_Y}_a4.png"
    pdf_path = boards_dir / f"charuco_{SQUARES_X}x{SQUARES_Y}_a4.pdf"
    canvas.save(png_path, dpi=(DPI, DPI))
    canvas.save(pdf_path, "PDF", resolution=float(DPI))

    yaml_path = cfg_dir / "charuco_params.yaml"
    yaml_path.write_text(
        "# ChArUco board parameters — paired with the printed PDF.\n"
        "# Generated by generate_charuco_board.py — regenerate if any value changes.\n"
        f"squares_x: {SQUARES_X}\n"
        f"squares_y: {SQUARES_Y}\n"
        f"square_length_m: {SQUARE_LENGTH_MM / 1000.0}\n"
        f"marker_length_m: {MARKER_LENGTH_MM / 1000.0}\n"
        f"aruco_dict: {DICT_NAME}\n"
        f"aruco_dict_id: {int(DICT_ID)}\n"
    )

    print(f"PNG : {png_path}")
    print(f"PDF : {pdf_path}")
    print(f"YAML: {yaml_path}")
    print()
    print("Mit 100% Skalierung drucken (fit-to-page AUS).")
    print("Nach dem Druck mit dem Lineal vergleichen — ein Quadrat = 30.0 mm muss sein.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
